timeout : '6000'
#reporter: 'spec'
package: './package.json'
parallel: true
recursive: true
reporter : 'mochawesome'
require: 'mochawesome/register'
reporter-option: [
   reportFilename: 'mochawesome-reports',
   quiet: true,
   html: true
]


