timeout : '60000'
#reporter: 'spec'
package: './package.json'
parallel: true
recursive: true
reporter : 'mochawesome'
require: 'mochawesome/register'
reporterOptions: [
   reportFilename: 'mochawesome-reports',
   quiet: true,
   html: true,
   json: true
]


