name : Mocha tests

on : 
    push : 
        branches: 
            - master

jobs : 
    test : 
        runs-on : self-hosted
        steps : 
            - name : Check out repo
              uses : actions/checkout@v4
              
            - name : NodeJs
              uses : actions/setup-node@v4

            - name: Caching and installing dependencies
              uses: mdasifnasin/node-js-cache-and-dependencies-install@1.0-Alpha
              with:
                path_of_the_file: node_modules

            - name : Run the tests
              run : npm test  
              
            - name: Upload Mochawesome Report as Artifact
              uses: actions/upload-artifact@v4
              with:
                name: mochawesome-report
                path: mochawesome-report/
              continue-on-error: true

            - name: Test Report
              uses: phoenix-actions/test-reporting@v8
              id: test-report               # Set ID reference for step
              if: success() || failure()    # run this step even if previous step failed
              with:
                name: Mocha Tests            # Name of the check run which will be created
                path: mochawesome-report/mochawesome.json    # Path to test results
                reporter: mocha-json
            
